//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESUFileExplorer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EAST STROUDSBURG UNIVERSITY OF PENNSYLVANIA")]
        public string CERT {
            get {
                return ((string)(this["CERT"]));
            }
            set {
                this["CERT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Shemp;0;https://shemp.esu.edu;/{0}/</string>
  <string>Cleo;1;https://cleo.esu.edu;/</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LOCATIONS {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LOCATIONS"]));
            }
            set {
                this["LOCATIONS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool REMEMBER_ME {
            get {
                return ((bool)(this["REMEMBER_ME"]));
            }
            set {
                this["REMEMBER_ME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool REMEMBER_LOCATION {
            get {
                return ((bool)(this["REMEMBER_LOCATION"]));
            }
            set {
                this["REMEMBER_LOCATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Open")]
        public string DOUBLE_CLICK_ACTION {
            get {
                return ((string)(this["DOUBLE_CLICK_ACTION"]));
            }
            set {
                this["DOUBLE_CLICK_ACTION"] = value;
            }
        }
    }
}
